$mainMod = SUPER

# https://wiki.hyprland.org/Configuring/Binds/
bind = $mainMod, X, killactive
bind = $mainMod, V, togglefloating
bind = $mainMod, D, togglesplit, # dwindle
bind = $mainMod, SPACE, exec, kitty
bind = $mainMod SHIFT, L, exec, wlogout
bind = $mainMod, N, exec, nemo
bind = $mainMod, F, exec, firefox
bind = CTRL, SPACE, exec, wofi
bind = $mainMod, M, exec, wp
bind = $mainMod, S, exec, grim -g "$(slurp)" - | swappy -f - # take a screenshot

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9

# Scroll through existing workspaces with mainMod + scroll
bind = ALT, L, workspace, e+1
bind = $mainMod, Right, workspace, e+1
bind = ALT, H, workspace, e-1
bind = $mainMod, Left, workspace, e-1

# Move/resize windows
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Fn keys
binde = , XF86MonBrightnessUp, exec, brightnessctl s +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
binde = , XF86AudioRaiseVolume, exec, pamixer -u --allow-boost -i 5
binde = , XF86AudioLowerVolume, exec, pamixer --allow-boost -d 5
bindr = , XF86AudioMute, exec, pamixer -t
