-- local mark = require("harpoon.mark")
-- local ui = require("harpoon.ui")
--
-- vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "[A]dd file to Harpoon" })
-- vim.keymap.set("n", "<leader>hm", ui.toggle_quick_menu, { desc = "Toggle Harpoon [M]enu" })
--
-- -- jump between files with Ctrl-$num
-- vim.keymap.set("n", "<c-1>", function() ui.nav_file(1) end)
-- vim.keymap.set("n", "<c-2>", function() ui.nav_file(2) end)
-- vim.keymap.set("n", "<c-3>", function() ui.nav_file(3) end)
-- vim.keymap.set("n", "<c-4>", function() ui.nav_file(4) end)
-- vim.keymap.set("n", "<c-5>", function() ui.nav_file(5) end)
-- vim.keymap.set("n", "<c-6>", function() ui.nav_file(6) end)
